### PR TITLE
Design fixes

### PR DESCRIPTION
**Pull request by Drakeoon**

### CODE REVIEW

**Comment by Drakeoon** [comment]
Check whether you like responsiveness from first commit better or the other, don't merge yet since i'll be adding more design fixes tomorrow

**Comment by AlanPieczonka** [comment]
Oh man, this looks sick!
The only thing that I'd change is the order of the boards - In my view user should always see the chart first, then the additional stuff (so on desktops the board with the chart will be on left side and other boards on the right and on mobiles the chart will go first). The other thing that I think we should think about is the non-logged users. On mobile devices everything is fine, but on devices with higher resolution there is a white blank space next to the chart, where it should take the whole space IMHO.
Oh, and also in my opinion the actual title of the vote should have Typography with variant "headline" instead of "title", it just looks a bit smoother for me.
If you want I will make these changes myself, just let me know how you want to go with it and if you want to make any more design fixes at this point. 
I won't update the backend until these changes will be merged so we can keep the same API and prepareChart function that needs to be adjusted. 
Once again, HUGE props for you ;) Cheers!

**Comment by Drakeoon** [comment]
- Changed the layout of components (chart to the left, panel to the right)
- Non-logged in users now can see chart aligned to the center
- Typography type changed to headline
- Added Font Awesome icons (since material ones seem to be very basic)
- Added responsive Grid in places where everything was just taking full space
- Made some small code adjustments

I think that my fixes are ready at this point, if you have any more issues/suggestions, please let me know :smiley:

**Comment by AlanPieczonka** [comment]
Man, I can't even say how good this code is. Hands down. Thank you so much. I really admire this UI. The only thing that I had to adjust is the connection of shareOnTwitter, deletePoll and addNewOption functions with RightPanel component and unecessary(?) Typography tag in the PollsList component. Once again, HUGE PROPS for you, cheers!

**Pull request merged**
